import 'package:shopping/controller/favorite_controller.dart';

class FavoritesModels {
  final int id;
  final bool isFavorite;
  final String title;
  final String image;
  final String price;

  FavoritesModels({
    required this.image,
    required this.title,
    required this.id,
    required this.price,
    required this.isFavorite,
  });

}
  List favoriteProduct = [
    {
      "id": 1,
      "isFavorite":  ,
      "title": "Ps5",
      "price": '499.99\$',
      "image": 'assets/images/product1.png',
    },
    {
      "id": 2,
      "isFavorite": false,
      "title": "Drone",
      "price": '159.99\$',
      "image": 'assets/images/product2.png',
    },
    {
      "id": 3,
      "isFavorite": false,
      "title": "Beats Studio",
      "price": '59.99\$',
      "image": 'assets/images/product3.png',
    },
    {
      "id": 4,
      "isFavorite": false,
      "title": "Alexa",
      "price": '79.99\$',
      "image": 'assets/images/product4.png',
    },
    {
      "id": 5,
      "isFavorite": false,
      "title": "Smart Watch",
      "price": '429.99\$',
      "image": 'assets/images/product5.png',
    },
    {
      "id": 6,
      "isFavorite": false,
      "title": "Garde Tools",
      "price": '39.99\$',
      "image": 'assets/images/product6.png',
    },
    {
      "id": 7,
      "isFavorite": false,
      "title": "AeroGarden Bounty Basic Indoor Hydroponic Herb Garden, Black",
      "price": '19.99\$',
      "image": 'assets/images/product7.png',
    },
    {
      "id": 8,
      "isFavorite": false,
      "title": "Shoes Nike",
      "price": '79.99\$',
      "image": 'assets/images/product8.png',
    },
    {
      "id": 9,
      "isFavorite": false,
      "title": "Te Shirt Cristiano with Portugal",
      "price": '99.99\$',
      "image": 'assets/images/product9.png',
    },
    {
      "id": 10,
      "isFavorite": false,
      "title": "Covergirl olay",
      "price": '11.99\$',
      "image": 'assets/images/product10.png',
    },
    {
      "id": 11,
      "isFavorite": false,
      "title": "Culler Beauty",
      "price": '29.99\$',
      "image": 'assets/images/product11.png',
    },
    {
      "id": 12,
      "isFavorite": false,
      "title": "Chair White",
      "price": '319.99\$',
      "image": 'assets/images/product12.png',
    },
    {
      "id": 13,
      "isFavorite": false,
      "title": "Laptop Notebook",
      "price": '799.99\$',
      "image": 'assets/images/product13.png',
    },
    {
      "id": 14,
      "isFavorite": false,
      "title": "Laptop Gaming Asus",
      "price": '1,459.99\$',
      "image": 'assets/images/product14.png',
    },
    {
      "id": 15,
      "isFavorite": false,
      "title": "Laptop Gaming Msi",
      "price": '1,299.99\$',
      "image": 'assets/images/product15.png',
    },
    {
      "id": 16,
      "isFavorite": false,
      "title": "Control Ps5",
      "price": '99.99\$',
      "image": 'assets/images/product16.png',
    },
    {
      "id": 17,
      "isFavorite": false,
      "title": "Beats Studio Black",
      "price": '129.99\$',
      "image": 'assets/images/product17.png',
    },
    {
      "id": 18,
      "isFavorite": false,
      "title": "Samsung Note 20 ultra",
      "price": '849.99\$',
      "image": 'assets/images/product18.png',
    },
    {
      "id": 19,
      "isFavorite": false,
      "title": "Huawei",
      "price": '899.99\$',
      "image": 'assets/images/product19.png',
    },
    {
      "id": 20,
      "isFavorite": false,
      "title": "Smart watch",
      "price": '499.99\$',
      "image": 'assets/images/product20.png',
    },
    {
      "id": 21,
      "isFavorite": false,
      "title": "Motherboard Msi",
      "price": '499.99\$',
      "image": 'assets/images/product21.png',
    },
    {
      "id": 22,
      "isFavorite": false,
      "title": "Motherboard Asus",
      "price": '449.99\$',
      "image": 'assets/images/product22.png',
    },
    {
      "id": 23,
      "isFavorite": false,
      "title": "Motherboard Gigabyte",
      "price": '429.99\$',
      "image": 'assets/images/product23.png',
    },
    {
      "id": 24,
      "isFavorite": false,
      "title": "Motherboard Asrock",
      "price": '319.99\$',
      "image": 'assets/images/product24.png',
    },
    {
      "id": 25,
      "isFavorite": false,
      "title": "CorsairRam 16Gb",
      "price": '179.99\$',
      "image": 'assets/images/product25.png',
    },
    {
      "id": 26,
      "isFavorite": false,
      "title": "G-Skill Ram 16Gb",
      "price": '159.99\$',
      "image": 'assets/images/product26.png',
    },
    {
      "id": 27,
      "isFavorite": false,
      "title": "Adata Ram 8Gb",
      "price": '59.99\$',
      "image": 'assets/images/product27.png',
    },
    {
      "id": 28,
      "isFavorite": false,
      "title": "T-Force Ram 8Gb",
      "price": '79.99\$',
      "image": 'assets/images/product28.png',
    },
    {
      "id": 29,
      "isFavorite": false,
      "title": "iPhone 13 Pro Max",
      "price": '1,099.99\$',
      "image": 'assets/images/product29.png',
    },
    {
      "id": 30,
      "isFavorite": false,
      "title": "iPhone 11 Pro Max",
      "price": '849.99\$',
      "image": 'assets/images/product30.png',
    },
    {
      "id": 31,
      "isFavorite": false,
      "title": "Msi Rtx 3070 8Gb",
      "price": '1,099.99\$',
      "image": 'assets/images/product31.png',
    },
    {
      "id": 32,
      "isFavorite": false,
      "title": "Asus Rtx 3070 8Gb",
      "price": '1,049.99\$',
      "image": 'assets/images/product32.png',
    },
    {
      "id": 33,
      "isFavorite": false,
      "title": "GigaByte Rtx 3070 8Gb",
      "price": '999.99\$',
      "image": 'assets/images/product33.png',
    },
    {
      "id": 34,
      "isFavorite": false,
      "title": "Zotac Rtx 3070 8Gb",
      "price": '949.99\$',
      "image": 'assets/images/product34.png',
    },
    {
      "id": 35,
      "isFavorite": false,
      "title": "Laptop Gaming Hp Omen",
      "price": '1,499.99\$',
      "image": 'assets/images/product35.png',
    },
    {
      "id": 36,
      "isFavorite": false,
      "title": "Laptop Make-Up",
      "price": '49.99\$',
      "image": 'assets/images/product36.png',
    },
    {
      "id": 37,
      "isFavorite": false,
      "title": "Laptop Make-Up Water",
      "price": '19.99\$',
      "image": 'assets/images/product37.png',
    },
    {
      "id": 38,
      "isFavorite": false,
      "title": "Rog",
      "price": '15.99\$',
      "image": 'assets/images/product38.png',
    },
    {
      "id": 39,
      "isFavorite": false,
      "title": "Rog",
      "price": '59.99\$',
      "image": 'assets/images/product39.png',
    },
    {
      "id": 40,
      "isFavorite": false,
      "title": "iLiner Pinsel",
      "price": '79.99\$',
      "image": 'assets/images/product40.png',
    },
    {
      "id": 41,
      "isFavorite": false,
      "title": "iLiner",
      "price": '29.99\$',
      "image": 'assets/images/product41.png',
    },
    {
      "id": 42,
      "isFavorite": false,
      "title": "Bodra",
      "price": '39.99\$',
      "image": 'assets/images/product42.png',
    },
    {
      "id": 43,
      "isFavorite": false,
      "title": "Laptop Make-Up",
      "price": '119.99\$',
      "image": 'assets/images/product43.png',
    },
    {
      "id": 44,
      "isFavorite": false,
      "title": "Laptop Make-Up Eye",
      "price": '79.99\$',
      "image": 'assets/images/product44.png',
    },
    {
      "id": 45,
      "isFavorite": false,
      "title": "iShadow",
      "price": '69.99\$',
      "image": 'assets/images/product45.png',
    },
    {
      "id": 46,
      "isFavorite": false,
      "title": "t Shirt",
      "price": '21.99\$',
      "image": 'assets/images/product46.png',
    },
    {
      "id": 47,
      "isFavorite": false,
      "title": "Sport Clothes",
      "price": '29.99\$',
      "image": 'assets/images/product47.png',
    },
    {
      "id": 48,
      "isFavorite": false,
      "title": "Shoes Black",
      "price": '59.99\$',
      "image": 'assets/images/product48.png',
    },
    {
      "id": 49,
      "isFavorite": false,
      "title": "Shoes Nike",
      "price": '99.99\$',
      "image": 'assets/images/product49.png',
    },
    {
      "id": 50,
      "isFavorite": false,
      "title": "Shoes Nike",
      "price": '59.99\$',
      "image": 'assets/images/product50.png',
    },
    {
      "id": 51,
      "isFavorite": false,
      "title": "Shoes Puma",
      "price": '59.99\$',
      "image": 'assets/images/product51.png',
    },
    {
      "id": 52,
      "isFavorite": false,
      "title": "Car BMW",
      "price": '40,499.99\$',
      "image": 'assets/images/product52.png',
    },
    {
      "id": 53,
      "isFavorite": false,
      "title": "Car Sport",
      "price": '1,400,429.99\$',
      "image": 'assets/images/product53.png',
    },
    {
      "id": 54,
      "isFavorite": false,
      "title": "Car Jeep",
      "price": '20,499.99\$',
      "image": 'assets/images/product54.png',
    },
    {
      "id": 55,
      "isFavorite": false,
      "title": "Car Classic",
      "price": '60,499.99\$',
      "image": 'assets/images/product55.png',
    },
    {
      "id": 56,
      "isFavorite": false,
      "title": "Chair",
      "price": '79.99\$',
      "image": 'assets/images/product56.png',
    },
    {
      "id": 57,
      "isFavorite": false,
      "title": "Chair Gaming",
      "price": '399.99\$',
      "image": 'assets/images/product57.png',
    },
    {
      "id": 58,
      "isFavorite": false,
      "title": "Chair Houses",
      "price": '99.99\$',
      "image": 'assets/images/product58.png',
    },
    {
      "id": 59,
      "isFavorite": false,
      "title": "Chair Moving",
      "price": '159.99\$',
      "image": 'assets/images/product59.png',
    },
    {
      "id": 60,
      "isFavorite": false,
      "title": "Tennis Racket",
      "price": '119.99\$',
      "image": 'assets/images/product60.png',
    },
    {
      "id": 61,
      "isFavorite": false,
      "title": "Table tennis",
      "price": '699.99\$',
      "image": 'assets/images/product61.png',
    },
    {
      "id": 62,
      "isFavorite": false,
      "title": "Bock Business",
      "price": '15.99\$',
      "image": 'assets/images/product62.png',
    },
    {
      "id": 63,
      "isFavorite": false,
      "title": "Backpack grey",
      "price": '59.99\$',
      "image": 'assets/images/product63.png',
    },
    {
      "id": 64,
      "isFavorite": false,
      "title": "Backpack black",
      "price": '79.99\$',
      "image": 'assets/images/product64.png',
    },
    {
      "id": 65,
      "isFavorite": false,
      "title": "Drone",
      "price": '429.99\$',
      "image": 'assets/images/product65.png',
    },
  ];
