class ProductsModels {
  final int id;
  final String title;
  final String image;
  final String price;

  ProductsModels(
      {required this.image,
      required this.title,
      required this.id,
      required this.price
      });
}

const List products = [
  {
    "id": 1,
    "title": "Ps5",
    "price": '499.99\$',
    "image": 'assets/images/product1.png',
  },
  {
    "id": 2,
    "title": "Drone",
    "price": '159.99\$',
    "image": 'assets/images/product2.png',
  },
  {
    "id": 3,
    "title": "Beats Studio",
    "price": '59.99\$',
    "image": 'assets/images/product3.png',
  },
  {
    "id": 4,
    "title": "Alexa",
    "price": '79.99\$',
    "image": 'assets/images/product4.png',
  },
  {
    "id": 5,
    "title": "Smart Watch",
    "price": '429.99\$',
    "image": 'assets/images/product5.png',
  },
  {
    "id": 6,
    "title": "Garde Tools",
    "price": '39.99\$',
    "image": 'assets/images/product6.png',
  },
  {
    "id": 7,
    "title": "AeroGarden Bounty Basic Indoor Hydroponic Herb Garden, Black",
    "price": '19.99\$',
    "image": 'assets/images/product7.png',
  },
  {
    "id": 8,
    "title": "Shoes Nike",
    "price": '79.99\$',
    "image": 'assets/images/product8.png',
  },
  {
    "id": 9,
    "title": "Te Shirt Cristiano with Portugal",
    "price": '99.99\$',
    "image": 'assets/images/product9.png',
  },
  {
    "id": 10,
    "title": "Covergirl olay",
    "price": '11.99\$',
    "image": 'assets/images/product10.png',
  },
  {
    "id": 11,
    "title": "Culler Beauty",
    "price": '29.99\$',
    "image": 'assets/images/product11.png',
  },
  {
    "id": 12,
    "title": "Chair White",
    "price": '319.99\$',
    "image": 'assets/images/product12.png',
  },
  {
    "id": 13,
    "title": "Laptop Notebook",
    "price": '799.99\$',
    "image": 'assets/images/product13.png',
  },
  {
    "id": 14,
    "title": "Laptop Gaming Asus",
    "price": '1,459.99\$',
    "image": 'assets/images/product14.png',
  },
  {
    "id": 15,
    "title": "Laptop Gaming Msi",
    "price": '1,299.99\$',
    "image": 'assets/images/product15.png',
  },
  {
    "id": 16,
    "title": "Control Ps5",
    "price": '99.99\$',
    "image": 'assets/images/product16.png',
  },
  {
    "id": 17,
    "title": "Beats Studio Black",
    "price": '129.99\$',
    "image": 'assets/images/product17.png',
  },
  {
    "id": 18,
    "title": "Samsung Note 20 ultra",
    "price": '849.99\$',
    "image": 'assets/images/product18.png',
  },
  {
    "id": 19,
    "title": "Huawei",
    "price": '899.99\$',
    "image": 'assets/images/product19.png',
  },
  {
    "id": 20,
    "title": "Smart watch",
    "price": '499.99\$',
    "image": 'assets/images/product20.png',
  },
  {
    "id": 21,
    "title": "Motherboard Msi",
    "price": '499.99\$',
    "image": 'assets/images/product21.png',
  },
  {
    "id": 22,
    "title": "Motherboard Asus",
    "price": '449.99\$',
    "image": 'assets/images/product22.png',
  },
  {
    "id": 23,
    "title": "Motherboard Gigabyte",
    "price": '429.99\$',
    "image": 'assets/images/product23.png',
  },
  {
    "id": 24,
    "title": "Motherboard Asrock",
    "price": '319.99\$',
    "image": 'assets/images/product24.png',
  },
  {
    "id": 25,
    "title": "CorsairRam 16Gb",
    "price": '179.99\$',
    "image": 'assets/images/product25.png',
  },
  {
    "id": 26,
    "title": "G-Skill Ram 16Gb",
    "price": '159.99\$',
    "image": 'assets/images/product26.png',
  },
  {
    "id": 27,
    "title": "Adata Ram 8Gb",
    "price": '59.99\$',
    "image": 'assets/images/product27.png',
  },
  {
    "id": 28,
    "title": "T-Force Ram 8Gb",
    "price": '79.99\$',
    "image": 'assets/images/product28.png',
  },
  {
    "id": 29,
    "title": "iPhone 13 Pro Max",
    "price": '1,099.99\$',
    "image": 'assets/images/product29.png',
  },
  {
    "id": 30,
    "title": "iPhone 11 Pro Max",
    "price": '849.99\$',
    "image": 'assets/images/product30.png',
  },
  {
    "id": 31,
    "title": "Msi Rtx 3070 8Gb",
    "price": '1,099.99\$',
    "image": 'assets/images/product31.png',
  },
  {
    "id": 32,
    "title": "Asus Rtx 3070 8Gb",
    "price": '1,049.99\$',
    "image": 'assets/images/product32.png',
  },
  {
    "id": 33,
    "title": "GigaByte Rtx 3070 8Gb",
    "price": '999.99\$',
    "image": 'assets/images/product33.png',
  },
  {
    "id": 34,
    "title": "Zotac Rtx 3070 8Gb",
    "price": '949.99\$',
    "image": 'assets/images/product34.png',
  },
  {
    "id": 35,
    "title": "Laptop Gaming Hp Omen",
    "price": '1,499.99\$',
    "image": 'assets/images/product35.png',
  },
  {
    "id": 36,
    "title": "Laptop Make-Up",
    "price": '49.99\$',
    "image": 'assets/images/product36.png',
  },
  {
    "id": 37,
    "title": "Laptop Make-Up Water",
    "price": '19.99\$',
    "image": 'assets/images/product37.png',
  },
  {
    "id": 38,
    "title": "Rog",
    "price": '15.99\$',
    "image": 'assets/images/product38.png',
  },
  {
    "id": 39,
    "title": "Rog",
    "price": '59.99\$',
    "image": 'assets/images/product39.png',
  },
  {
    "id": 40,
    "title": "iLiner Pinsel",
    "price": '79.99\$',
    "image": 'assets/images/product40.png',
  },
  {
    "id": 41,
    "title": "iLiner",
    "price": '29.99\$',
    "image": 'assets/images/product41.png',
  },
  {
    "id": 42,
    "title": "Bodra",
    "price": '39.99\$',
    "image": 'assets/images/product42.png',
  },
  {
    "id": 43,
    "title": "Laptop Make-Up",
    "price": '119.99\$',
    "image": 'assets/images/product43.png',
  },
  {
    "id": 44,
    "title": "Laptop Make-Up Eye",
    "price": '79.99\$',
    "image": 'assets/images/product44.png',
  },
  {
    "id": 45,
    "title": "iShadow",
    "price": '69.99\$',
    "image": 'assets/images/product45.png',
  },
  {
    "id": 46,
    "title": "t Shirt",
    "price": '21.99\$',
    "image": 'assets/images/product46.png',
  },
  {
    "id": 47,
    "title": "Sport Clothes",
    "price": '29.99\$',
    "image": 'assets/images/product47.png',
  },
  {
    "id": 48,
    "title": "Shoes Black",
    "price": '59.99\$',
    "image": 'assets/images/product48.png',
  },
  {
    "id": 49,
    "title": "Shoes Nike",
    "price": '99.99\$',
    "image": 'assets/images/product49.png',
  },
  {
    "id": 50,
    "title": "Shoes Nike",
    "price": '59.99\$',
    "image": 'assets/images/product50.png',
  },
  {
    "id": 51,
    "title": "Shoes Puma",
    "price": '59.99\$',
    "image": 'assets/images/product51.png',
  },
  {
    "id": 52,
    "title": "Car BMW",
    "price": '40,499.99\$',
    "image": 'assets/images/product52.png',
  },
  {
    "id": 53,
    "title": "Car Sport",
    "price": '1,400,429.99\$',
    "image": 'assets/images/product53.png',
  },
  {
    "id": 54,
    "title": "Car Jeep",
    "price": '20,499.99\$',
    "image": 'assets/images/product54.png',
  },
  {
    "id": 55,
    "title": "Car Classic",
    "price": '60,499.99\$',
    "image": 'assets/images/product55.png',
  },
  {
    "id": 56,
    "title": "Chair",
    "price": '79.99\$',
    "image": 'assets/images/product56.png',
  },
  {
    "id": 57,
    "title": "Chair Gaming",
    "price": '399.99\$',
    "image": 'assets/images/product57.png',
  },
  {
    "id": 58,
    "title": "Chair Houses",
    "price": '99.99\$',
    "image": 'assets/images/product58.png',
  },
  {
    "id": 59,
    "title": "Chair Moving",
    "price": '159.99\$',
    "image": 'assets/images/product59.png',
  },
  {
    "id": 60,
    "title": "Tennis Racket",
    "price": '119.99\$',
    "image": 'assets/images/product60.png',
  },
  {
    "id": 61,
    "title": "Table tennis",
    "price": '699.99\$',
    "image": 'assets/images/product61.png',
  },
  {
    "id": 62,
    "title": "Bock Business",
    "price": '15.99\$',
    "image": 'assets/images/product62.png',
  },
  {
    "id": 63,
    "title": "Backpack grey",
    "price": '59.99\$',
    "image": 'assets/images/product63.png',
  },
  {
    "id": 64,
    "title": "Backpack black",
    "price": '79.99\$',
    "image": 'assets/images/product64.png',
  },
  {
    "id": 65,
    "title": "Drone",
    "price": '429.99\$',
    "image": 'assets/images/product65.png',
  },
];
